# Global values (sẽ được override bởi file dev/values.yaml hoac prod/values.yaml)
global:
  imageRegistry: ""
  namespace: "default"

# Thiết lập an toàn mặc định
replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: "latest"

fullnameOverride: ""
nameOverride: ""

containerPort: 8080 # Phù hợp với Dockerfile của dự án

service:
  type: ClusterIP
  port: 80

migration:
  enabled: false
  dllName: ""

env: {}
secretEnv: {}
livenessProbe: {}
readinessProbe: {}

keyvault:
  enabled: false
  secretsMap: {}

# Workload Identities mapping (mặc định rỗng, override ở dev/prod)
workloadIdentities: {}

keyvault_clients: {}