@Tracker.TaskService_HostAddress = http://localhost:5002

GET {{Tracker.TaskService_HostAddress}}/health
Accept: application/json

###

GET {{Tracker.TaskService_HostAddress}}/api/v1/tasks
Accept: application/json
Authorization: Bearer {{$dotenv ACCESS_TOKEN}}

###