apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "microservice.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "microservice.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.keyvault.enabled }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      serviceAccountName: {{ include "microservice.fullname" . }} # Tên ServiceAccount
      containers:
        - name: {{ include "microservice.fullname" . }}
          # Lấy Registry từ biến global, ghép với tên repository và tag
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.global.imageTag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }} # Sẽ là 8080 cho Backend, thay đổi tuỳ service
              protocol: TCP

          {{- if or .Values.env .Values.keyvault.enabled }}
          envFrom:
            {{- if .Values.env }}
            - configMapRef:
                name: {{ include "microservice.fullname" . }}-config
            {{- end }}
            {{- if .Values.keyvault.enabled }}
            - secretRef:
                name: {{ include "microservice.fullname" . }}-synced-secret
            {{- end }}
          {{- end }}

          # THÊM MỚI: Mount ổ đĩa ảo của CSI
          {{- if .Values.keyvault.enabled }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          {{- end }}

          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}

      # Khai báo Volume cho CSI
      {{- if .Values.keyvault.enabled }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "microservice.fullname" . }}-akv
      {{- end }}