{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "microservice.fullname" . }}-migration
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    metadata:
      name: {{ include "microservice.fullname" . }}-migration
    spec:
      # Job không bao giờ tự restart nếu lỗi mã code, để ta còn check log
      restartPolicy: Never
      containers:
        - name: db-migration
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.global.imageTag | default .Values.image.tag }}"
          # Chèn thêm argument --migrate vào lệnh chạy DLL
          command: ["dotnet", "{{ .Values.migration.dllName }}", "--migrate"]
          # Tái sử dụng lại toàn bộ biến môi trường của ứng dụng để kết nối DB
          {{- if or .Values.env .Values.secretEnv }}
          envFrom:
            {{- if .Values.env }}
            - configMapRef:
                name: {{ include "microservice.fullname" . }}-config
            {{- end }}
            {{- if .Values.secretEnv }}
            - secretRef:
                name: {{ include "microservice.fullname" . }}-secret
            {{- end }}
          {{- end }}
{{- end }}