{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "microservice.fullname" . }}-migration
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 300 # Thêm field tự động dọn dẹp Job sau 300 giây (5 phút)
  template:
    metadata:
      name: {{ include "microservice.fullname" . }}-migration
      labels:
        {{- include "microservice.labels" . | nindent 6 }}
        {{- if .Values.keyvault.enabled }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      serviceAccountName: {{ include "microservice.fullname" . }}
      # Job không bao giờ tự restart nếu lỗi mã code, để ta còn check log
      restartPolicy: Never
      containers:
        - name: db-migration
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.global.imageTag | default .Values.image.tag }}"
          # Chèn thêm argument --migrate vào lệnh chạy DLL
          command: ["dotnet", "{{ .Values.migration.dllName }}", "--migrate"]

          # Mount Volume CSI cho Job
          {{- if .Values.keyvault.enabled }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          {{- end }}

          {{- if or .Values.env .Values.secretEnv .Values.keyvault.enabled }}
          envFrom:
            {{- if .Values.env }}
            - configMapRef:
                name: {{ include "microservice.fullname" . }}-config
            {{- end }}
            {{- if .Values.secretEnv }}
            - secretRef:
                name: {{ include "microservice.fullname" . }}-secret
            {{- end }}
            # Nạp Synced Secret
            {{- if .Values.keyvault.enabled }}
            - secretRef:
                name: {{ include "microservice.fullname" . }}-synced-secret
            {{- end }}
          {{- end }}

      # Khai báo Volume CSI cho Job
      {{- if .Values.keyvault.enabled }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "microservice.fullname" . }}-akv
      {{- end }}
{{- end }}