{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "microservice.fullname" . }}-migration
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    # Báo cho Helm biết đây là một Hook chạy trước khi cài hoặc nâng cấp
    "helm.sh/hook": pre-install,pre-upgrade
    # Mức độ ưu tiên, số nhỏ chạy trước (-5 chạy trước 0)
    "helm.sh/hook-weight": "-5"
    # Xóa job cũ trước khi tạo job mới, và xóa job nếu chạy thành công
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "microservice.fullname" . }}-migration
    spec:
      # Job không bao giờ tự restart nếu lỗi mã code, để ta còn check log
      restartPolicy: Never
      containers:
        - name: db-migration
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.global.imageTag | default .Values.image.tag }}"
          # Chèn thêm argument --migrate vào lệnh chạy DLL
          command: ["dotnet", "{{ .Values.migration.dllName }}", "--migrate"]
          # Tái sử dụng lại toàn bộ biến môi trường của ứng dụng để kết nối DB
          {{- if .Values.env }}
          envFrom:
            - configMapRef:
                name: {{ include "microservice.fullname" . }}-config
          {{- end }}
{{- end }}