{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
type: Opaque
data:
  # Dùng b64enc để tự động mã hóa giá trị sang Base64
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}