{{- if .Values.keyvault.enabled }}

# THAY MỚI: Lấy Client ID từ cấu trúc workloadIdentities dựa vào tên service
{{- $clientId := dig "workloadIdentities" (include "microservice.fullname" .) "MISSING-CLIENT-ID" .Values }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "microservice.fullname" . }}-akv
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Giữ nguyên wave 0 để tạo trước
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    
    clientID: "{{ $clientId }}" # Lấy Client ID từ cấu trúc workloadIdentities dựa vào tên service
    keyvaultName: "{{ .Values.global.keyvaultName }}"
    tenantId: "{{ .Values.global.tenantId }}"
    # Duyệt qua danh sách các secret cần lấy từ Key Vault
    objects:  |
      array:
        {{- range $kvSecretName, $envVarName := .Values.keyvault.secretsMap }}
        - |
          objectName: "{{ $kvSecretName }}"
          objectType: secret
          objectVersion: ""
        {{- end }}
  # Ánh xạ các secret lấy về thành K8s Secret để bơm vào biến môi trường
  secretObjects:
  - secretName: {{ include "microservice.fullname" . }}-synced-secret
    type: Opaque
    data:
    {{- range $kvSecretName, $envVarName := .Values.keyvault.secretsMap }}
    - key: {{ $envVarName }}
      objectName: "{{ $kvSecretName }}"
    {{- end }}
{{- end }}