apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
  annotations:
    # Nối K8s ServiceAccount với Azure Identity Client ID
    azure.workload.identity/client-id: "{{ .Values.keyvault.clientId }}"