{{- $cm := lookup "v1" "ConfigMap" (default .Release.Namespace .Values.global.namespace) "workload-identity-client-ids" }}
{{- $clientId := "" }}
{{- if $cm }}
  {{- $clientId = index $cm.data (include "microservice.fullname" .) | default "" }}
{{- end }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "{{ $clientId }}"