apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
    # BỌC LẠI BẰNG IF: Chỉ thêm label nếu keyvault enabled
    {{- if .Values.keyvault.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
  {{- if .Values.keyvault.enabled }}
  annotations:
    # DÙNG HÀM INDEX: Tìm Client ID trong map keyvault_clients dựa trên tên service
    azure.workload.identity/client-id: "{{ index .Values.keyvault_clients (include "microservice.fullname" .) }}"
  {{- end }}