# CHỈ tạo chứng chỉ nếu cờ wildcardCert.enabled được bật
{{- if .Values.wildcardCert.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.global.domainPrefix }}-wildcard-cert
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # Tên K8s Secret sẽ chứa chứng chỉ TLS sau khi xin thành công.
  # Các Ingress sau này sẽ trỏ vào cái tên secret này.
  secretName: wildcard-tls-secret
  issuerRef:
    # Trỏ đúng vào tên ClusterIssuer Production mà ta đã tạo
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  # Xin chứng chỉ cho domain gốc và tất cả các subdomain cấp 1
  - "*.{{ .Values.global.domainName }}"
  - "{{ .Values.global.domainName }}"
{{- end }}