global:
  imageRegistry: "acrtasktrackerdev4459.azurecr.io"
  namespace: "dev"
  imageTag: "f799b711517030b2cf1c0330626e2889be61977f" # Đổi tag 1 LẦN Ở ĐÂY, 7 service tự cập nhật!

replicaCount: 1 # Ở dev chỉ cần 1 pod để tiết kiệm tiền