global:
  imageRegistry: "acrtasktrackerdev4459.azurecr.io"
  namespace: "dev"
  imageTag: "10d764e4cf4ac8e64af1453bf73a97fa31bc6d6c" # Đổi tag 1 LẦN Ở ĐÂY, 7 service tự cập nhật!

replicaCount: 1 # Ở dev chỉ cần 1 pod để tiết kiệm tiền