<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Tracker.CommentService</RootNamespace>
    <UserSecretsId>tracker-comment-service</UserSecretsId>
  </PropertyGroup>

</Project>
