apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.14.4
      helm:
        valueFiles:
          - $values/deploy/environments/dev/cert-manager-values.yaml
    - repoURL: 'https://github.com/kudoshinichi2k5/MyTaskTracker.git'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'
        - '.webhooks[].namespaceSelector.matchExpressions'
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'
        - '.webhooks[].namespaceSelector.matchExpressions'