fullnameOverride: "admin-portal"
image:
  repository: "frontend/adminportal"
  tag: ""
service:
  port: 80
env: {} # Frontend SPA Nginx không cần truyền biến môi trường Runtime kiểu backend

# KHAI BÁO PROBE CHO NGINX
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5