fullnameOverride: "auth-service" # Định danh cố định để các service khác gọi
image:
  # Tên repo đã lowercase như Week 6
  repository: "backend/authservice" 
  # Hãy dán cái Git SHA (VD: d55ac27d3a31568cf5aa5ea76d732c0c97c32f9f) bạn lấy từ ACR vào đây
  tag: "d55ac27d3a31568cf5aa5ea76d732c0c97c32f9f"

service:
  port: 80 # Bên ngoài cụm nội bộ gọi port 80, K8s sẽ trỏ vào containerPort 8080