fullnameOverride: "comment-service"
image:
  repository: "backend/commentservice"
  tag: "11a010945053f4345708a41359f78d63c3a89546"
service:
  port: 80
env:
  ASPNETCORE_ENVIRONMENT: "Development"

secretEnv:
  ConnectionStrings__CommentDb: "Server=tracker-mariadb.dev.svc.cluster.local;Port=3306;Database=tracker_comments;User=comment_service;Password=newcommentpassword888;"
  AuthService__BaseUrl: "http://auth-service"
  AuthService__VerifyPath: "/verify"
  AllowedFrontendOrigins: "http://localhost:4200,http://localhost:4300"

migration:
  enabled: true
  dllName: "Tracker.CommentService.dll"

# KHAI BÁO PROBE CHO .NET
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10