fullnameOverride: "comment-service"
image:
  repository: "backend/commentservice"
  tag: "latest"
service:
  port: 80
env:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__CommentDb: "Server=tracker-mariadb.dev.svc.cluster.local;Port=3306;Database=tracker_comments;User=comment_service;Password=devcommentpassword;"
  AuthService__BaseUrl: "http://auth-service"
  AuthService__VerifyPath: "/verify"
  AllowedFrontendOrigins: "http://localhost:4200,http://localhost:4300"

# KHAI BÁO PROBE CHO .NET
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10