fullnameOverride: "notification-service"
image:
  repository: "backend/notificationservice"
service:
  port: 80
env:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__NotificationDb: "Server=tracker-mariadb.dev.svc.cluster.local;Port=3306;Database=tracker_notifications;User=notification_service;Password=devnotificationpassword;"
  AuthService__BaseUrl: "http://auth-service"
  AuthService__VerifyPath: "/verify"
  AllowedFrontendOrigins: "http://localhost:4200,http://localhost:4300"

# KHAI BÁO PROBE CHO .NET
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10