fullnameOverride: "notification-service"
image:
  repository: "backend/notificationservice"
  tag: "820e67b7062aafcabd2dce6a7cb5e0419c5b3f29"
service:
  port: 80
env:
  ASPNETCORE_ENVIRONMENT: "Development"

# secretEnv:
#   ConnectionStrings__NotificationDb: "Server=tracker-mariadb.dev.svc.cluster.local;Port=3306;Database=tracker_notifications;User=notification_service;Password=newnotificationpassword888;"
#   AuthService__BaseUrl: "http://auth-service"
#   AuthService__VerifyPath: "/verify"
#   AllowedFrontendOrigins: "http://localhost:4200,http://localhost:4300"

keyvault:
  enabled: true
  secretsMap:
    # Key: Tên Secret được lưu trong Azure Key Vault (Bạn phải tạo thủ công trên Portal)
    # Value: Tên Biến Môi Trường sẽ được K8s bơm vào cho ứng dụng .NET
    "notification-service-connection-string": "ConnectionStrings__NotificationDb"

migration:
  enabled: true
  dllName: "Tracker.NotificationService.dll"

# KHAI BÁO PROBE CHO .NET
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10