fullnameOverride: "notification-service"
image:
  repository: "backend/notificationservice"
  tag: "83322643943f1a85cd597626d10118cfb43d908a"
service:
  port: 80
env:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__NotificationDb: "Server=tracker-mariadb.dev.svc.cluster.local;Port=3306;Database=tracker_notifications;User=notification_service;Password=devnotificationpassword;"
  AuthService__BaseUrl: "http://auth-service"
  AuthService__VerifyPath: "/verify"
  AllowedFrontendOrigins: "http://localhost:4200,http://localhost:4300"

migration:
  enabled: true
  dllName: "Tracker.NotificationService.dll"

# KHAI BÁO PROBE CHO .NET
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10