fullnameOverride: "project-service"
image:
  repository: "backend/projectservice"
  tag: "d6a64255a1237ef0fce8512d098a701dcdb9cf50"
service:
  port: 80
env:
  ASPNETCORE_ENVIRONMENT: "Development"

secretEnv:
  ConnectionStrings__ProjectDb: "Server=tracker-mariadb.dev.svc.cluster.local;Port=3306;Database=tracker_projects;User=project_service;Password=newprojectpassword888;"
  AuthService__BaseUrl: "http://auth-service"
  AuthService__VerifyPath: "/verify"
  AllowedFrontendOrigins: "http://localhost:4200,http://localhost:4300"

migration:
  enabled: true
  dllName: "Tracker.ProjectService.dll"

# KHAI BÁO PROBE CHO .NET
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10