fullnameOverride: "project-service"
image:
  repository: "backend/projectservice"
service:
  port: 80
env:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__ProjectDb: "Server=tracker-mariadb.dev.svc.cluster.local;Port=3306;Database=tracker_projects;User=project_service;Password=devprojectpassword;"
  AuthService__BaseUrl: "http://auth-service"
  AuthService__VerifyPath: "/verify"
  AllowedFrontendOrigins: "http://localhost:4200,http://localhost:4300"

# KHAI BÁO PROBE CHO .NET
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10