name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# BẮT BUỘC: Khai báo quyền để GitHub Actions có thể xin token OIDC
permissions:
  id-token: write 
  contents: read  

# Khai báo các thông số kết nối với Azure (Nên dùng GitHub Secrets trong thực tế, nhưng hiện tại hardcode để dễ test)
env:
  AZURE_CLIENT_ID: "d5f6a163-cfbe-4a4f-bb94-10b6df792363"
  AZURE_TENANT_ID: "2dff09ac-2b3b-4182-9953-2b548e0d0b39"
  AZURE_SUBSCRIPTION_ID: "7d87cfd2-0799-41e4-838a-0ea3b2b7f96d"

jobs:
  setup-and-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Test Azure CLI
        run: az account show